name: Tasks

settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: "br.com.mrss."
  deploymentTarget: "13.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"

targets:
  Tasks:
    platform: iOS
    type: application
    sources:
      - path: Tasks
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: Tasks
      INFOPLIST_FILE: Tasks/Info.plist
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE: "Wildcard"

schemes:
  Tasks:
    build:
      targets:
        Tasks: [run]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug