name: Tasks
options:
  bundleIdPrefix: "br.com.mrss.Tasks"
  deploymentTarget: "12.0"
  createIntermediateGroups: true
targetTemplates:
  Default:
targets:
  "Tasks":
principal:
  templates: Default
  type: framework
  platform: iOS
  sources: ["Tasks"]
  dependencies: []